# Generated by Django 5.1.5 on 2025-02-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productnew', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
